// flow-typed signature: 4ec76f53b7ac27f434ab09bb90cc8e16
// flow-typed version: <<STUB>>/react-cache_v^2.0.0-alpha.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cache/cjs/react-cache.development' {
  declare module.exports: any;
}

declare module 'react-cache/cjs/react-cache.production.min' {
  declare module.exports: any;
}

declare module 'react-cache/umd/react-cache.development' {
  declare module.exports: any;
}

declare module 'react-cache/umd/react-cache.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cache/cjs/react-cache.development.js' {
  declare module.exports: $Exports<'react-cache/cjs/react-cache.development'>;
}
declare module 'react-cache/cjs/react-cache.production.min.js' {
  declare module.exports: $Exports<'react-cache/cjs/react-cache.production.min'>;
}
declare module 'react-cache/index' {
  declare module.exports: $Exports<'react-cache'>;
}
declare module 'react-cache/index.js' {
  declare module.exports: $Exports<'react-cache'>;
}
declare module 'react-cache/umd/react-cache.development.js' {
  declare module.exports: $Exports<'react-cache/umd/react-cache.development'>;
}
declare module 'react-cache/umd/react-cache.production.min.js' {
  declare module.exports: $Exports<'react-cache/umd/react-cache.production.min'>;
}
